
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { ReactLenis } from "lenis/react"; // 👈 add this
import localFont from "next/font/local";
import CustomCursor from "@/components/CustomCursor";
import Footer from "@/components/layout/Footer";

const neueHaas = localFont({
  src: "./fonts/NeueHaasDisplayMedium.ttf",
  weight: "500",
  variable: "--font-neue-haas",
  
});

const abcArizona = localFont({
  src: "./fonts/ABCArizonaSerif-Light.ttf",
  weight: "400",
  variable: "--font-abc-arizona",
})

const oldSchool = localFont({
  src: "./fonts/OldschoolGrotesk-NormalRegular.otf",
  weight: "400",
  variable: "--font-old-school",
})

const rlMadena = localFont({
  src: "./fonts/RL-Madena.otf",
  weight: "100",
  variable: "--font-rl-madena",
})

const montreal = localFont({
  src: "./fonts/Montreal Bold.otf",
  weight: "400",
  variable: "--font-montreal",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${neueHaas.className} ${abcArizona.variable} ${oldSchool.variable} ${rlMadena.variable} ${montreal.variable} antialiased `}>
        <CustomCursor />
        <ReactLenis root> 
          <Navbar />
          {children}
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}